# Generated by Django 3.2.9 on 2022-01-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20220112_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='usertaskprofile',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
